name: "Publish Artifacts"
description: Publishes the build artifacts
inputs:
  artifact-name:
    description: Artifact name
    required: true
runs:
  using: composite
  steps:
    - name: Upload build
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: src/build/bin/*
        if-no-files-found: error
