// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function ConfirmOrganization() {
  return window['go']['app']['App']['ConfirmOrganization']();
}

export function GetMissingDLC() {
  return window['go']['app']['App']['GetMissingDLC']();
}

export function GetMissingGames() {
  return window['go']['app']['App']['GetMissingGames']();
}

export function GetMissingUpdates() {
  return window['go']['app']['App']['GetMissingUpdates']();
}

export function GetOrganizationPreview() {
  return window['go']['app']['App']['GetOrganizationPreview']();
}

export function IsKeysFileAvailable() {
  return window['go']['app']['App']['IsKeysFileAvailable']();
}

export function LoadSettings() {
  return window['go']['app']['App']['LoadSettings']();
}

export function OrganizeLibrary() {
  return window['go']['app']['App']['OrganizeLibrary']();
}

export function RescanLibrary(arg1) {
  return window['go']['app']['App']['RescanLibrary'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function ShowInFolder(arg1) {
  return window['go']['app']['App']['ShowInFolder'](arg1);
}

export function ShowMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ShowMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateDB() {
  return window['go']['app']['App']['UpdateDB']();
}

export function UpdateLocalLibrary(arg1) {
  return window['go']['app']['App']['UpdateLocalLibrary'](arg1);
}
