name: "Build App"
description: Builds the app
inputs:
  platform:
    description: Wails target platform
    required: true
runs:
  using: composite
  steps:
    - name: Generate Wails bindings
      working-directory: ./src
      shell: bash
      run: wails generate module

    - name: Prepare application icon
      working-directory: ./src
      shell: bash
      run: mkdir -p build && cp assets/icons/icon.png build/appicon.png

    - name: Build with Wails
      working-directory: ./src
      shell: bash
      run: wails build -platform "${{ inputs.platform }}" -webview2 embed
