// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['GUI']['CheckUpdate']();
}

export function ConfirmOrganization() {
  return window['go']['main']['GUI']['ConfirmOrganization']();
}

export function GetMissingDLC() {
  return window['go']['main']['GUI']['GetMissingDLC']();
}

export function GetMissingGames() {
  return window['go']['main']['GUI']['GetMissingGames']();
}

export function GetMissingUpdates() {
  return window['go']['main']['GUI']['GetMissingUpdates']();
}

export function IsKeysFileAvailable() {
  return window['go']['main']['GUI']['IsKeysFileAvailable']();
}

export function LoadSettings() {
  return window['go']['main']['GUI']['LoadSettings']();
}

export function OrganizeLibrary() {
  return window['go']['main']['GUI']['OrganizeLibrary']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['GUI']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['GUI']['SelectFolder']();
}

export function ShowInFolder(arg1) {
  return window['go']['main']['GUI']['ShowInFolder'](arg1);
}

export function ShowMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['GUI']['ShowMessage'](arg1, arg2, arg3, arg4);
}

export function Start() {
  return window['go']['main']['GUI']['Start']();
}

export function UpdateDB() {
  return window['go']['main']['GUI']['UpdateDB']();
}

export function UpdateLocalLibrary(arg1) {
  return window['go']['main']['GUI']['UpdateLocalLibrary'](arg1);
}

export function UpdateProgress(arg1, arg2, arg3) {
  return window['go']['main']['GUI']['UpdateProgress'](arg1, arg2, arg3);
}
