name: Build master

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            artifact: switch-library-manager.windows-amd64
          - os: ubuntu-22.04
            platform: linux/amd64
            artifact: switch-library-manager.linux-amd64
          - os: macos-15-intel
            platform: darwin/amd64
            artifact: switch-library-manager.darwin-amd64
          - os: macos-15
            platform: darwin/arm64
            artifact: switch-library-manager.darwin-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build app
        uses: ./.github/actions/build-app
        with:
          platform: ${{ matrix.platform }}

      - name: Publish artifacts
        uses: ./.github/actions/publish-artifacts
        with:
          artifact-name: ${{ matrix.artifact }}
