name: Verify PR

on:
  pull_request:
    branches:
     - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      uses: ./.github/actions/setup-environment

    - name: Build app
      uses: ./.github/actions/build-app